const ActionType = {
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_FORUMS: 'RECEIVE_FORUM',
  SET_IS_PRELOAD: 'SET_IS_PRELOAD',
};

export { ActionType };
