const ActionType = {
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_THREADS: 'RECEIVE_THREADS',
  ADD_THREADS: 'ADD_THREADS',
  CLEAR_THREADS: 'CLEAR_THREADS',
  SET_IS_PRELOAD: 'SET_IS_PRELOAD',
  RECEIVE_LEADERBOARDS: 'RECEIVE_LEADERBOARDS',
  CLEAR_LEADERBOARDS: 'CLEAR_LEADERBOARDS',
  SET_FILTERED: 'SET_FILTERED',
  TOGGLE_FILTERED_THREAD_BY_CATEGORY: 'TOGGLE_FILTERED_THREAD_BY_CATEGORY',

};

export { ActionType };
