const ActionType = {
  SET_AUTH_USER: 'SET_AUTH_USER',
  UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',

  RECEIVE_THREADS: 'RECEIVE_THREADS',
  ADD_THREADS: 'ADD_THREADS',
  CLEAR_THREADS: 'CLEAR_THREADS',

  RECEIVE_DETAIL_THREADS: 'RECEIVE_DETAIL_THREADS',
  CLEAR_THREAD_DETAIL: 'CLEAR_THREAD_DETAIL',

  SET_FILTERED: 'SET_FILTERED',
  TOGGLE_FILTERED_THREAD_BY_CATEGORY: 'TOGGLE_FILTERED_THREAD_BY_CATEGORY',

  RECEIVE_COMMENTS: 'RECEIVE_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
  CLEAR_COMMENTS: 'CLEAR_COMMENTS',

  UP_VOTE_THREAD: 'UP_VOTE_THREAD',
  DOWN_VOTE_THREAD: 'DOWN_VOTE_THREAD',
  NEUTRALIZE_VOTE_THREAD: 'NEUTRALIZE_VOTE_THREAD',
  FILTER_VOTE_THREAD: 'FILTER_VOTE_THREAD',

  UP_VOTE_THREAD_DETAIL: 'UP_VOTE_THREAD_DETAIL',
  DOWN_VOTE_THREAD_DETAIL: 'DOWN_VOTE_THREAD_DETAIL',
  NEUTRALIZE_VOTE_THREAD_DETAIL: 'NEUTRALIZE_VOTE_THREAD_DETAIL',

  UP_VOTE_COMMENT: 'UP_VOTE_COMMENT',
  DOWN_VOTE_COMMENT: 'DOWN_VOTE_COMMENT',
  NEUTRALIZE_VOTE_COMMENT: 'NEUTRALIZE_VOTE_COMMENT',

  RECEIVE_LEADERBOARDS: 'RECEIVE_LEADERBOARDS',
  CLEAR_LEADERBOARDS: 'CLEAR_LEADERBOARDS',

  SET_IS_PRELOAD: 'SET_IS_PRELOAD',

};

export { ActionType };
